# Created using wingetcreate 1.12.13.0
# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.12.0.schema.json

PackageIdentifier: getSigit.siGitCode
PackageVersion: 1.6.6
InstallerType: portable
Commands:
- sigit
Installers:
- Architecture: x64
  InstallerUrl: https://github.com/getsigit/sigit/releases/download/v1.6.6/sigit-win-amd64.exe
  InstallerSha256: B580EB8E8644B3730071DF8F7B095440AFE1432AC65EAF4223465BD54A60C809
  Dependencies:
    PackageDependencies:
    - PackageIdentifier: Microsoft.VCRedist.2015+.x64
- Architecture: arm64
  InstallerUrl: https://github.com/getsigit/sigit/releases/download/v1.6.6/sigit-win-arm64.exe
  InstallerSha256: 6306BDDD2BEAF786AF9CDDA1A7DA0DAF61D1727624DBE0487E5D879949ADC5FE
  Dependencies:
    PackageDependencies:
    - PackageIdentifier: Microsoft.VCRedist.2015+.arm64
ManifestType: installer
ManifestVersion: 1.12.0
ReleaseDate: 2026-10-09
