# Created using wingetcreate 1.12.13.0
# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.12.0.schema.json

PackageIdentifier: getSigit.siGitCode
PackageVersion: 1.6.0
InstallerType: portable
Commands:
- sigit
Installers:
- Architecture: x64
  InstallerUrl: https://github.com/getsigit/sigit/releases/download/v1.6.0/sigit-win-amd64.exe
  InstallerSha256: 776C7BDDA15B4F5F4B4D2A161696F0C865284537369D712B43D4F12BC268E9EE
  Dependencies:
    PackageDependencies:
    - PackageIdentifier: Microsoft.VCRedist.2015+.x64
- Architecture: arm64
  InstallerUrl: https://github.com/getsigit/sigit/releases/download/v1.6.0/sigit-win-arm64.exe
  InstallerSha256: EAB25E9C76159BC9A0BA6741685499774BCFBA50FF97C752A1469080D9CE2D16
  Dependencies:
    PackageDependencies:
    - PackageIdentifier: Microsoft.VCRedist.2015+.arm64
ManifestType: installer
ManifestVersion: 1.12.0
ReleaseDate: 2026-10-05
