# Created using wingetcreate 1.12.13.0
# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.12.0.schema.json

PackageIdentifier: getSigit.siGitCode
PackageVersion: 1.6.1
InstallerType: portable
Commands:
- sigit
Installers:
- Architecture: x64
  InstallerUrl: https://github.com/getsigit/sigit/releases/download/v1.6.1/sigit-win-amd64.exe
  InstallerSha256: 49517F5FA8E70A0ECD06693137625470D43E7D0595E605690E6BF8F8AF055E5A
  Dependencies:
    PackageDependencies:
    - PackageIdentifier: Microsoft.VCRedist.2015+.x64
- Architecture: arm64
  InstallerUrl: https://github.com/getsigit/sigit/releases/download/v1.6.1/sigit-win-arm64.exe
  InstallerSha256: 71FB16A6B0846361A61DF70A8B34493051178DA727355E3205FBA68BBFD034AE
  Dependencies:
    PackageDependencies:
    - PackageIdentifier: Microsoft.VCRedist.2015+.arm64
ManifestType: installer
ManifestVersion: 1.12.0
ReleaseDate: 2026-10-05
