# Created using wingetcreate 1.12.13.0
# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.12.0.schema.json

PackageIdentifier: getSigit.siGitCode
PackageVersion: 1.6.2
InstallerType: portable
Commands:
- sigit
Installers:
- Architecture: x64
  InstallerUrl: https://github.com/getsigit/sigit/releases/download/v1.6.2/sigit-win-amd64.exe
  InstallerSha256: AF53ABD8CF8AB4EC017100C966DF5B9A228BF6D1C0F66C91C1C023082BE3E4DD
  Dependencies:
    PackageDependencies:
    - PackageIdentifier: Microsoft.VCRedist.2015+.x64
- Architecture: arm64
  InstallerUrl: https://github.com/getsigit/sigit/releases/download/v1.6.2/sigit-win-arm64.exe
  InstallerSha256: B547A1F215588A0FF98ADD62778B5CCC8623C88BD25B9C582389E6F569D0EDAE
  Dependencies:
    PackageDependencies:
    - PackageIdentifier: Microsoft.VCRedist.2015+.arm64
ManifestType: installer
ManifestVersion: 1.12.0
ReleaseDate: 2026-10-06
