# Created using wingetcreate 1.12.13.0
# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.12.0.schema.json

PackageIdentifier: getSigit.siGitCode
PackageVersion: 1.6.3
InstallerType: portable
Commands:
- sigit
Installers:
- Architecture: x64
  InstallerUrl: https://github.com/getsigit/sigit/releases/download/v1.6.3/sigit-win-amd64.exe
  InstallerSha256: 7F98089CC36A12FBED5D8099D75632420C3E7425BC185C745F8AE8653F2964D1
  Dependencies:
    PackageDependencies:
    - PackageIdentifier: Microsoft.VCRedist.2015+.x64
- Architecture: arm64
  InstallerUrl: https://github.com/getsigit/sigit/releases/download/v1.6.3/sigit-win-arm64.exe
  InstallerSha256: CC2AF5AB6ECB9B139DB35BE64623AB03B3BEC03DEDFC39BDE73A803DD1DAC6C8
  Dependencies:
    PackageDependencies:
    - PackageIdentifier: Microsoft.VCRedist.2015+.arm64
ManifestType: installer
ManifestVersion: 1.12.0
ReleaseDate: 2026-10-06
